#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://travis-ci.org/
# * native R support: https://github.com/craigcitro/r-travis
# * examples: https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis
# * r-builder: https://github.com/metacran/r-builder
# * covr: https://github.com/jimhester/covr
# * Coveralls: https://coveralls.io/
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
# sudo: required
# before_install:
#   - sudo apt-get -qq update
#   - sudo apt-get install -y libicu-dev
#   - sudo apt-get install -y pandoc
# r_binary_packages:
#   - methods
#   - statmod
#   - stats
#   - graphics
#   - RCurl
#   - jsonlite
#   - tools
#   - utils
#   - assertthat
#   - doParallel
#   - data.table
#   - dplyr
#   - foreach
#   - ggplot2
#   - magrittr
#   - knitr
#   - R6
#   - Rcpp
#   - rmarkdown
#   - RUnit
#   - speedglm
#   - tibble
#   - tidyr
#   - pander
#   - purrr
#   - zoo

language: r
sudo: false
cache: packages
warnings_are_errors: false
# r_build_args: "--compact-vignettes"
# r_check_args: "--as-cran"
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --as-cran"

os:
  - linux
  # - osx

r_github_packages:
  - jimhester/covr
  - schloerke/travisDrat
  - osofr/gridisl

# r_packages:
#   - ggiraph
# - xgboost
# - bindata

addons:
  apt:
    packages:
      - libicu-dev
      - pandoc

env:
 global:
   - CRAN: http://cran.rstudio.com

after_success:
  - Rscript -e 'covr::coveralls()'

# - Rscript -e "packagedocs::deploy_travis()"
# - Rscript -e "travisDrat::deploy_drat()"

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

